# gcc-plugin.m4 -*- Autoconf -*-
# Check whether GCC is able to be built with plugin support.

dnl Copyright (C) 2014 Free Software Foundation, Inc.
dnl This file is free software, distributed under the terms of the GNU
dnl General Public License.  As a special exception to the GNU General
dnl Public License, this file may be distributed as part of a program
dnl that contains a configuration script generated by Autoconf, under
dnl the same distribution terms as the rest of that program.

# Check for plugin support.
# Respects --enable-plugin.
# Sets the shell variables enable_plugin and pluginlibs.
AC_DEFUN([GCC_ENABLE_PLUGINS],
  [# Check for plugin support
   AC_ARG_ENABLE(plugin,
   [AS_HELP_STRING([--enable-plugin], [enable plugin support])],
   enable_plugin=$enableval,
   enable_plugin=yes; default_plugin=yes)

   pluginlibs=
   plugin_check=yes

   case "${host}" in
     *-*-mingw*)
       # Since plugin support under MinGW is not as straightforward as on
       # other platforms (e.g., we have to link import library, etc), we
       # only enable it if explicitly requested.
       if test x"$default_plugin" = x"yes"; then
         enable_plugin=no
       elif test x"$enable_plugin" = x"yes"; then
         # Use make's target variable to derive import library name.
         pluginlibs='-Wl,--export-all-symbols -Wl,--out-implib=[$]@.a'
	 plugin_check=no
       fi
     ;;
     *-*-darwin*)
       if test x$build = x$host; then
	 export_sym_check="nm${exeext} -g"
       elif test x$host = x$target; then
	 export_sym_check="$gcc_cv_nm -g"
       else
	 export_sym_check=
       fi
     ;;
     *)
       if test x$build = x$host; then
	 export_sym_check="$ac_cv_prog_OBJDUMP -T"
       elif test x$host = x$target; then
	 export_sym_check="$gcc_cv_objdump -T"
       else
	 export_sym_check="$ac_cv_prog_OBJDUMP -T"
       fi
     ;;
   esac

   if test x"$enable_plugin" = x"yes" -a x"$plugin_check" = x"yes"; then

     AC_MSG_CHECKING([for exported symbols])
     if test "x$export_sym_check" != x; then
       echo "int main() {return 0;} int foobar() {return 0;}" > conftest.c
       ${CC} ${CFLAGS} ${LDFLAGS} conftest.c -o conftest$ac_exeext > /dev/null 2>&1
       if $export_sym_check conftest$ac_exeext | grep foobar > /dev/null; then
	 : # No need to use a flag
	 AC_MSG_RESULT([yes])
       else
	 AC_MSG_RESULT([yes])
	 AC_MSG_CHECKING([for -rdynamic])
	 ${CC} ${CFLAGS} ${LDFLAGS} -rdynamic conftest.c -o conftest$ac_exeext > /dev/null 2>&1
	 if $export_sym_check conftest$ac_exeext | grep foobar > /dev/null; then
	   plugin_rdynamic=yes
	   pluginlibs="-rdynamic"
	 else
	   plugin_rdynamic=no
	   enable_plugin=no
	 fi
	 AC_MSG_RESULT([$plugin_rdynamic])
       fi
     else
       AC_MSG_RESULT([unable to check])
     fi

     # Check -ldl
     saved_LIBS="$LIBS"
     AC_SEARCH_LIBS([dlopen], [dl])
     if test x"$ac_cv_search_dlopen" = x"-ldl"; then
       pluginlibs="$pluginlibs -ldl"
     fi
     LIBS="$saved_LIBS"

     # Check that we can build shared objects with -fPIC -shared
     saved_LDFLAGS="$LDFLAGS"
     saved_CFLAGS="$CFLAGS"
     saved_CXXFLAGS="$CXXFLAGS"
     case "${host}" in
       *-*-darwin*)
	 CFLAGS=`echo $CFLAGS | sed s/-mdynamic-no-pic//g`
	 CFLAGS="$CFLAGS -fPIC"
	 CXXFLAGS=`echo $CXXFLAGS | sed s/-mdynamic-no-pic//g`
	 CXXFLAGS="$CXXFLAGS -fPIC"
	 LDFLAGS="$LDFLAGS -shared -undefined dynamic_lookup"
       ;;
       *)
	 CFLAGS="$CFLAGS -fPIC"
	 CXXFLAGS="$CXXFLAGS -fPIC"
	 LDFLAGS="$LDFLAGS -fPIC -shared"
       ;;
     esac
     AC_MSG_CHECKING([for -fPIC -shared])
     AC_TRY_LINK(
       [extern int X;],[return X == 0;],
       [AC_MSG_RESULT([yes]); have_pic_shared=yes],
       [AC_MSG_RESULT([no]); have_pic_shared=no])
     if test x"$have_pic_shared" != x"yes" -o x"$ac_cv_search_dlopen" = x"no"; then
       pluginlibs=
       enable_plugin=no
     fi
     LDFLAGS="$saved_LDFLAGS"
     CFLAGS="$saved_CFLAGS"
     CXXFLAGS="$saved_CXXFLAGS"

     # If plugin support had been requested but not available, fail.
     if test x"$enable_plugin" = x"no" ; then
       if test x"$default_plugin" != x"yes"; then
	 AC_MSG_ERROR([
   Building GCC with plugin support requires a host that supports
   -fPIC, -shared, -ldl and -rdynamic.])
       fi
     fi
   fi
])

dnl
dnl
dnl GCC_PLUGIN_OPTION
dnl    (SHELL-CODE_HANDLER)
dnl
AC_DEFUN([GCC_PLUGIN_OPTION],[dnl
AC_MSG_CHECKING([for -plugin option])

dnl Select names for the host tools.  The unversioned DLL names match
dnl gcc/config.host; retain the -0.dll names for older installations.
case "${host}" in
  *-*-cygwin*) plugin_names="cyglto_plugin.dll cyglto_plugin-0.dll" ;;
  *-*-msys*) plugin_names="msys-lto_plugin.dll msys-lto_plugin-0.dll" ;;
  *-*-mingw*) plugin_names="liblto_plugin.dll liblto_plugin-0.dll" ;;
  *) plugin_names="liblto_plugin.so" ;;
esac
plugin_option=
for plugin in $plugin_names; do
  plugin_so=`${CC} ${CFLAGS} --print-prog-name "$plugin"`
  if test "x$plugin_so" = "x$plugin"; then
    plugin_so=`${CC} ${CFLAGS} --print-file-name "$plugin"`
  fi
  if test "x$plugin_so" != "x$plugin"; then
    plugin_option="--plugin=$plugin_so"
    break
  fi
done
# Quote a value so a later `eval' sees it as exactly one word.
# AR and RANLIB are deliberately allowed to be command strings that carry
# their own arguments, so they must be re-parsed by the shell rather than
# quoted as a single word.  Re-parsing with `eval' also keeps a quoted
# executable path such as "/opt/my tools/ar" in one piece.  The values we
# append are therefore single-quoted here and pathname expansion is turned
# off around the call, so a plugin path containing spaces, glob characters,
# quotes or shell metacharacters reaches the tool as one argument and can
# never start a command of its own.
func_plugin_quote ()
{
  plugin_quoted=
  plugin_quote_rest=$plugin_quote_arg
  while :; do
    case $plugin_quote_rest in
      *\'*)
        plugin_quoted=$plugin_quoted${plugin_quote_rest%%\'*}"'\\''"
        plugin_quote_rest=${plugin_quote_rest#*\'} ;;
      *)
        plugin_quoted="'$plugin_quoted$plugin_quote_rest'"
        break ;;
    esac
  done
}
# Replace every occurrence of $plugin_subst_from in $plugin_subst_in with
# $plugin_subst_to, leaving the result in $plugin_subst_out.
func_plugin_subst ()
{
  plugin_subst_out=
  plugin_subst_rest=$plugin_subst_in
  while :; do
    case $plugin_subst_rest in
      *"$plugin_subst_from"*)
        plugin_subst_out=$plugin_subst_out${plugin_subst_rest%%"$plugin_subst_from"*}$plugin_subst_to
        plugin_subst_rest=${plugin_subst_rest#*"$plugin_subst_from"} ;;
      *)
        plugin_subst_out=$plugin_subst_out$plugin_subst_rest
        break ;;
    esac
  done
}
# Turn $plugin_make_arg into text that can be substituted into the AR or
# RANLIB command string of a generated makefile.  It has to survive make
# expansion and then the shell that runs the recipe, so quote it for the
# shell first, then double every dollar sign and escape every hash so make
# hands the shell back exactly the text we quoted.
#
# Makefiles also forward these command strings to sub-makes inside double
# quotes, as in "AR=$(AR)", and a double-quoted word still expands dollar
# signs and backquotes and is ended early by a double quote.  No single
# piece of text can be correct both there and in a bare recipe word, and a
# newline cannot be held in a makefile variable at all.  Values containing
# any of those four characters are therefore refused by returning an empty
# result, exactly as if the archiver had no plugin support, rather than
# being spliced in raw where they would be expanded or would run.
func_plugin_make_quote ()
{
  plugin_quote_arg=$plugin_make_arg; func_plugin_quote
  plugin_subst_in=$plugin_quoted
  plugin_subst_from='$'; plugin_subst_to='$$'; func_plugin_subst
  plugin_subst_in=$plugin_subst_out
  plugin_subst_from='#'; plugin_subst_to='\#'; func_plugin_subst
  plugin_make_quoted=$plugin_subst_out
  plugin_make_nl='
'
  case $plugin_make_arg in
    *"$plugin_make_nl"* | *'$'* | *'`'* | *'"'*) plugin_make_quoted= ;;
  esac
}
dnl Check if ${AR} "$plugin_option" rc works.
AC_CHECK_TOOL(AR, ar)
if test "${AR}" = "" ; then
  AC_MSG_ERROR([Required archive tool 'ar' not found on PATH.])
fi
if test -n "$plugin_option"; then
  touch conftest.c
  plugin_quote_arg=$plugin_option; func_plugin_quote
  (set -f; eval "${AR} $plugin_quoted rc conftest.a conftest.c")
  if test "$?" != 0; then
    AC_MSG_WARN([Failed: $AR "$plugin_option" rc])
    plugin_option=
  fi
  rm -f conftest.*
fi
if test -n "$plugin_option"; then
  $1="$plugin_option"
  AC_MSG_RESULT($plugin_option)
else
  AC_MSG_RESULT([no])
fi
])
